"""Domain analysis modules and experiment logic."""

from .push_laps import (
    PushLapSelector,
    add_push_lap_flags,
    fresh_tyre_mask,
    get_dominant_compound,
    select_dry_push_laps,
    select_top_drivers,
)
from .quali_performance import (
    QualiPerformanceAnalyzer,
    QualiPerformanceResult,
    calculate_quali_performance,
)
from .race_performance_review import (
    MonteCarloRacePerformanceAlgorithm,
    MonteCarloRacePerformanceConfig,
    MonteCarloRacePerformanceResult,
    RacePerformanceReviewAlgorithm,
    calculate_monte_carlo_race_performance_review,
    is_wet_race,
    summarize_monte_carlo_race_performance,
    wet_lap_proportion_by_driver,
)
from wostrategy.model.track_evolution import (
    EXPONENTIAL_TRACK_EVOLUTION_MODEL,
    LINEAR_TRACK_EVOLUTION_MODEL,
    TRACK_EVO_CORRECTED_LAP_TIME,
    TRACK_EVO_CORRECTED_LAP_TIME_SECONDS,
    TRACK_EVO_CORRECTION_SECONDS,
    TRACK_EVOLUTION_FIT_MODEL,
    TRACK_EVOLUTION_SECONDS_PER_LAP,
    ExponentialTrackEvolutionModel,
    LinearTrackEvolutionModel,
    TrackEvolutionFit,
    TrackEvolutionModel,
    add_track_evolution_correction,
    dominant_compound,
    fit_compound_track_evolution,
    get_track_evolution_model,
)

__all__ = [
    "EXPONENTIAL_TRACK_EVOLUTION_MODEL",
    "LINEAR_TRACK_EVOLUTION_MODEL",
    "TRACK_EVO_CORRECTED_LAP_TIME",
    "TRACK_EVO_CORRECTED_LAP_TIME_SECONDS",
    "TRACK_EVO_CORRECTION_SECONDS",
    "TRACK_EVOLUTION_FIT_MODEL",
    "TRACK_EVOLUTION_SECONDS_PER_LAP",
    "ExponentialTrackEvolutionModel",
    "LinearTrackEvolutionModel",
    "TrackEvolutionFit",
    "TrackEvolutionModel",
    "PushLapSelector",
    "QualiPerformanceAnalyzer",
    "QualiPerformanceResult",
    "MonteCarloRacePerformanceAlgorithm",
    "MonteCarloRacePerformanceConfig",
    "MonteCarloRacePerformanceResult",
    "RacePerformanceReviewAlgorithm",
    "add_track_evolution_correction",
    "add_push_lap_flags",
    "calculate_quali_performance",
    "calculate_monte_carlo_race_performance_review",
    "dominant_compound",
    "fit_compound_track_evolution",
    "fresh_tyre_mask",
    "get_dominant_compound",
    "get_track_evolution_model",
    "select_dry_push_laps",
    "select_top_drivers",
    "is_wet_race",
    "summarize_monte_carlo_race_performance",
    "wet_lap_proportion_by_driver",
]
